### ISSUE TITLE
Conversion error in scs2dd()

### ISSUE THREAD

**Issue by jrenfree** [SWFSC/surveyR#2]
If the input string only contains three digits after the decimal, then the "N" gets included in the value and the coercion to numeric results in an NA. For example, the following input latitude was obtained from the SCS system on Lasker:

"3442.012N"

**Comment by kstierhoff** [comment]
Updated the function to strip the non-numeric characters before parsing the string, thereby fixing the problem of including the "N" or "W" when precision changes.
